### ISSUE TITLE
Compatibility for globalize >= 5.0

### ISSUE THREAD

**Issue by ouelletv** [scarfacedeb/rails_admin_globalize_field#17]
Would be nice :)

**Comment by scarfacedeb** [comment]
@ouelletv yeah 😳, I can't find the time to check it out.
Some of the tests are failing with globalize >= 5.0 and it's most likely caused by monkey patching of rails internals.
I'll try to debug it next weekend.

**Comment by chaucerling** [comment]
@scarfacedeb Are you free to accept the PR

**Comment by ouelletv** [comment]
+1

**Comment by maximski** [comment]
+1

**Comment by scarfacedeb** [comment]
@maximski @ouelletv @chaucerling I accepted the PR. 
Sorry for the delay. I'm moving to another city at the moment.
