### ISSUE TITLE
Add validation for only one language 

### ISSUE THREAD

**Issue by maximski** [scarfacedeb/rails_admin_globalize_field#21]
Is there a way to add a validation to only one language, e.g. validate the presence of :title just for the :en locale?

**Comment by scarfacedeb** [comment]
@maximski I see 2 ways to make it work:

You can either create subclass of Translation yourself (globalize creates it under the hood), (e.g. `Brand::Translation`) with validation on `title` with `if: -> { |trans| trans.locale == :en }`.

Also you can add validation in the main model this way:
```
class Brand
   translate :title
   translation_class.validate :title, presence: true, if: -> { |trans| trans.locale == :en }
```

**Comment by maximski** [comment]
Alright, thanks! But globalize_field won't recognize that field as such (so it won't mark it as required in the form).

**Comment by scarfacedeb** [comment]
@maximski As far as I can tell, rails_admin doesn't take into account presence validations with `if:` options.
