### ISSUE TITLE
question: using :wysihtml5 (or other editor) 

### ISSUE THREAD

**Issue by jshow** [scarfacedeb/rails_admin_globalize_field#23]
Greetings,

Thank you for the very helpful addition to rails_admin

Is there a way I can use a wysiwyg editor for a translation field ?

cheers/Jodi

**Comment by scarfacedeb** [comment]
@jshow Hi,

Did you try specifying field type inside translation model?

```ruby
  config.model 'Page::Translation' do
    configure :content, :wysihtml5
    include_fields :locale, :title, :content
  end
```

**Comment by jshow** [comment]
thanks @scarfacedeb - I've jumped to activeadmin due to troubles with rails admin

I'll close
