### ISSUE TITLE
Duplicated fields

### ISSUE THREAD

**Issue by Strollager** [scarfacedeb/rails_admin_globalize_field#24]
Привет! Не могу понять, в readme на скринах поля не дублируются.
У меня же сначала показываются поля из стандартной локали, и после них появляются табы с переключением языка. Как сделать так, чтобы сначала выводились поля которые не участвуют в переводе, а потом появлялись табы с полями которые нужно переводить?

На скриншоте который я приложил, сначала же идут поля title, description и тд(из английско локали), и потом появляются табы с тем же самым, получается некое дублирование..

Post.rb
```ruby
class Post < ActiveRecord::Base
  translates :title, :description, :content, :meta_description
  accepts_nested_attributes_for :translations, allow_destroy: true
end
```

Post.rb
```ruby
RailsAdmin.config do |config|
  config.included_models = ['Post','Post::Translation']

  config.actions do
    dashboard                     # mandatory
    index                         # mandatory
    new
    export
    bulk_delete
    show
    edit
    delete
    show_in_app
  end

  config.model Post do
    include_fields :locale, :title, :description, :content, :meta_description
  end

  config.model 'Post::Translation' do
    visible false
    configure :locale, :hidden do
      help ''
    end
    include_fields :locale, :title, :description, :content, :meta_description
  end

end

```

![2015-11-29 14 13 57](https://cloud.githubusercontent.com/assets/11654565/11457627/f1bec494-96be-11e5-9f27-b521ef2f1df1.png)

**Comment by Strollager** [comment]
Это моя ошибка, я продублировал поля в таблице posts и posts_translations

**Comment by scarfacedeb** [comment]
Понятно, хорошо.
