### ISSUE TITLE
Translated field names

### ISSUE THREAD

**Issue by airled** [scarfacedeb/rails_admin_globalize_field#37]
Hi. Is it possible to use localized attribute names inside tab here?
![2019-10-16-163550_1366x768_scrot](https://user-images.githubusercontent.com/10863999/66911970-6fba7600-f033-11e9-9fe4-ee1dd873f5e0.png)
`Name` and `subtitle` are translated for my default locale (not en) via `ru/active_record/attributes/MY_MODEL/name` and `ru/active_record/attributes/MY_MODEL/subtitle`. Should I add anything else in locale files?

**Comment by scarfacedeb** [comment]
@airled Yes, it's possible. See: #32.

**Comment by airled** [comment]
Oh, so sorry for my inattention. Thansk a lot!
